server {
    listen 80;
    listen [::]:80;
    server_name panel.legacyhosting.xyz;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name panel.legacyhosting.xyz;

    ssl_certificate /etc/letsencrypt/live/panel.legacyhosting.xyz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/panel.legacyhosting.xyz/privkey.pem;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Content-Type-Options nosniff always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;
    add_header Permissions-Policy "camera=(), microphone=(), geolocation=()" always;

    root /var/www/legacy-hosting-panel;
    index index.html;

    location /assets/ {
        try_files $uri =404;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location / {
        try_files $uri /index.html;
        add_header Cache-Control "no-cache";
    }
}
