import React, {useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity, Box, ChevronDown, CircleHelp, Cloud, Code2, GitBranch, Globe2, LayoutDashboard, MoreHorizontal, Play, Plus, RefreshCw, Search, Server, Settings, ShieldCheck, Terminal, Users, Wifi} from 'lucide-react';
import './main.css';

const apps=[{name:'portal-api', domain:'api.legacyhosting.dev', node:'fra-01', status:'Running', cpu:'8.4%', mem:'214 MB', deploy:'2 min ago', color:'violet'},{name:'customer-dashboard', domain:'app.legacyhosting.dev', node:'fra-01', status:'Running', cpu:'3.1%', mem:'386 MB', deploy:'Yesterday', color:'blue'},{name:'billing-worker', domain:'worker.legacyhosting.dev', node:'ams-02', status:'Stopped', cpu:'—', mem:'—', deploy:'3 days ago', color:'orange'}];
const nav=[['Overview',LayoutDashboard],['Applications',Box],['Nodes',Server],['Domains',Globe2],['Deployments',GitBranch],['Team',Users]];
function App(){const [page,setPage]=useState('Overview'); const [query,setQuery]=useState(''); return <div className="shell"><aside><div className="brand"><div className="mark">L</div><div><strong>Legacy Hosting</strong><span>Control panel</span></div></div><div className="workspace"><div className="workspace-icon">N</div><div><b>Nextarch Studio</b><small>Personal workspace</small></div><ChevronDown size={15}/></div><nav>{nav.map(([label,Icon])=><button className={page===label?'active':''} onClick={()=>setPage(label)} key={label}><Icon size={17}/>{label}</button>)}</nav><div className="aside-bottom"><button onClick={()=>setPage('Settings')}><Settings size={17}/>Settings</button><button><CircleHelp size={17}/>Documentation</button><div className="profile"><div className="avatar">DA</div><div><b>DJ Ang</b><small>Owner</small></div><MoreHorizontal size={17}/></div></div></aside><main><header><div><div className="eyebrow">{page === 'Overview' ? 'Workspace overview' : page}</div><h1>{page==='Overview'?'Good afternoon, DJ':page}</h1></div><div className="header-actions"><button className="icon-btn"><Search size={18}/></button><button className="status"><span></span> All systems operational</button><button className="primary"><Plus size={17}/> New application</button></div></header><div className="scroll-content">{page==='Overview'?<Overview query={query}/>:<Placeholder page={page}/>}</div><Footer/></main></div>}
function Overview({query}){return <><section className="hero"><div><div className="hero-icon"><Activity size={22}/></div><h2>Your applications are healthy</h2><p>Monitor deployments, nodes, and domains from one place.</p></div><button className="secondary"><RefreshCw size={16}/> Refresh data</button></section><div className="stats"><Stat label="Applications" value="3" note="2 running" icon={Box}/><Stat label="Nodes" value="2" note="All online" icon={Server}/><Stat label="Domains" value="4" note="3 proxied" icon={Globe2}/><Stat label="Deployments" value="28" note="This month" icon={GitBranch}/></div><section className="section-head"><div><h3>Applications</h3><p>Live status across your workspace</p></div><div className="filters"><div className="search"><Search size={16}/><input placeholder="Search applications" value={query}/></div><button className="secondary">All statuses <ChevronDown size={15}/></button></div></section><div className="app-list">{apps.filter(a=>a.name.includes(query.toLowerCase())).map(a=><div className="app-row" key={a.name}><div className={'app-logo '+a.color}><Code2 size={19}/></div><div className="app-name"><b>{a.name}</b><span><Globe2 size={13}/>{a.domain}</span></div><div className="pill"><i className={a.status==='Running'?'green':'gray'}></i>{a.status}</div><div className="metric"><small>CPU</small><b>{a.cpu}</b></div><div className="metric"><small>Memory</small><b>{a.mem}</b></div><div className="deploy"><small>Last deployment</small><b>{a.deploy}</b></div><button className="row-action"><Play size={15}/></button><button className="row-action"><MoreHorizontal size={17}/></button></div>)}</div><div className="lower"><section className="card"><div className="card-title"><div><h3>Node health</h3><p>Resource usage across your infrastructure</p></div><button className="link">View nodes</button></div><Node name="fra-01" location="Frankfurt, DE" cpu="42" mem="61"/><Node name="ams-02" location="Amsterdam, NL" cpu="28" mem="38"/></section><section className="card"><div className="card-title"><div><h3>Recent activity</h3><p>Latest changes in your workspace</p></div><button className="link">View all</button></div><ActivityItem icon={GitBranch} text="portal-api deployed successfully" time="2 min ago"/><ActivityItem icon={Wifi} text="Node fra-01 connected" time="18 min ago"/><ActivityItem icon={ShieldCheck} text="Cloudflare DNS synced" time="1 hr ago"/></section></div></>}
function Stat({label,value,note,icon:Icon}){return <div className="stat"><div className="stat-icon"><Icon size={18}/></div><div><small>{label}</small><strong>{value}</strong><span>{note}</span></div></div>}; function Node({name,location,cpu,mem}){return <div className="node"><div className="node-symbol"><Server size={17}/></div><div className="node-info"><b>{name}</b><span>{location} · Online</span></div><div className="bar"><small>CPU <b>{cpu}%</b></small><div><i style={{width:cpu+'%'}}></i></div></div><div className="bar"><small>Memory <b>{mem}%</b></small><div><i style={{width:mem+'%'}}></i></div></div></div>}; function ActivityItem({icon:Icon,text,time}){return <div className="activity"><div><Icon size={16}/></div><span><b>{text}</b><small>{time}</small></span></div>}; function Placeholder({page}){return <div className="placeholder"><div className="hero-icon"><Terminal size={23}/></div><h2>{page} is ready for configuration</h2><p>This area will connect to the Legacy Hosting API and MySQL 8 data layer.</p><button className="primary"><Plus size={17}/> Add {page.toLowerCase().replace('s','')}</button></div>}
function Footer(){const [now,setNow]=useState(new Date()); React.useEffect(()=>{const timer=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(timer)},[]); const time=new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Oslo',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(now).replace(',',''); return <footer><span>LH-Panel v0.1.0</span><span>Copyright 2009 © {now.getFullYear()} <a href="https://legacyhosting.xyz" target="_blank" rel="noreferrer">Legacy Hosting</a></span><span>{time}</span></footer>}
createRoot(document.getElementById('root')).render(<App/>);

